life/gym/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.programs, name='gym'),
    path('clients_programs/', views.clients_programs, name='clients_programs'),
]

life/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from life.core import views

urlpatterns = [
    # path('summernote/', include('django_summernote.urls')),
    path('profile/', views.profile, name='profile'),
    path('account/delete_account/', views.delete_account, name='delete_account'),
    path('edit_goal/<pk>', views.edit_goal, name='edit_goal'),
    path('notes/', views.notes, name='notes'),
    path('delete_goal/<pk>', views.delete_goal, name='delete_goal'),
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('gym/', include('life.gym.urls')),
    path('', views.home, name='home'),
]

urlpatterns += [
    path("ckeditor5/", include('django_ckeditor_5.urls'), name="ck_editor_5_upload_file"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

life/core/models.py
from django.contrib.auth.models import User
from django.db import models
from django_ckeditor_5.fields import CKEditor5Field

from life.core import services


class Goal(models.Model):

    PROJECT, TRIP, BUY, DO = 'pr', 'tr', 'by', 'do'
    TYPES = ((PROJECT, 'Project'), (TRIP, 'Trip'), (BUY, 'Buy'), (DO, 'Do'))

    HIGH, LOW = 'hi', 'lo'
    EFFORTS = ((HIGH, 'High'), (LOW, 'Low'))

    PERSONAL, PROFESSIONAL = 'pe', 'pr'
    AREAS = ((PERSONAL, 'Personal'), (PROFESSIONAL, 'Professional'))

    PRIORITIES = ((1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'))

    user = models.ForeignKey(User, on_delete=models.CASCADE)

    name = models.CharField(max_length=255)
    description = models.TextField(blank=True, null=True)

    type = models.CharField(max_length=2, choices=TYPES)
    effort = models.CharField(max_length=2, choices=EFFORTS)
    area = models.CharField(max_length=2, choices=AREAS, default=PERSONAL)
    important = models.PositiveSmallIntegerField(choices=PRIORITIES, default='1')
    urgent = models.PositiveSmallIntegerField(choices=PRIORITIES, default='1')
    matrix = models.PositiveSmallIntegerField(default=0)

    cost = models.DecimalField(max_digits=12, decimal_places=2, null=True, blank=True)
    start_date = models.DateField()
    end_date = models.DateField(null=True, blank=True)
    next = models.BooleanField(default=False)
    completed = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)

    def save(self, *args, **kwargs):
        self.matrix = self.matrix_calculation()
        return super(Goal, self).save(*args, **kwargs)

    def matrix_calculation(self):
        matrix = self.important * self.urgent
        return matrix

    def __str__(self):
        return self.name


class GoogleAgenda(models.Model):

    user = models.OneToOneField(User, on_delete=models.CASCADE)
    agenda_id = models.TextField()
    agenda_clean = models.TextField(blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def save(self, *args, **kwargs):
        self.agenda_clean = services.extract_src_ctz(self.agenda_id)
        return super(GoogleAgenda, self).save(*args, **kwargs)

    def __str__(self):
        return f"{self.user}'s Google agenda"


class Notes(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    my_notes = CKEditor5Field(null=True, blank=True)

    def __str__(self):
        return f"{self.user}'s Notes"

    class Meta:
        verbose_name_plural = 'Notes'

life/gym/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _


class TrainingProgram(models.Model):
    """A program of exercises for a given user"""
    user = models.ForeignKey('auth.User', on_delete=models.CASCADE, verbose_name=_("Usuário"))
    name = models.CharField(max_length=100, verbose_name=_("Nome do programa"))
    active = models.BooleanField(default=True, verbose_name=_("Ativo"))
    created_at = models.DateTimeField(auto_now_add=True, verbose_name=_("Criado em"))

    class Meta:
        verbose_name = _("Programa do usuário")
        verbose_name_plural = _("Programas do usuário")

    def __str__(self):
        return f"{self.user.first_name} {self.user.last_name} - {self.name}"


class Exercise(models.Model):
    """The exercise itself."""
    name = models.CharField(max_length=100, verbose_name=_("Nome do Exercício"))
    video_url = models.URLField(blank=True, verbose_name=_("URL do Vídeo"))

    @property
    def embed_url(self):
        """
        Converts video_url to YouTube embed format.
        Supports:
        - https://youtube.com/watch?v=<video_id>
        - https://youtube.com/shorts/<video_id>
        - https://youtu.be/<video_id>
        Converts to:
        - https://www.youtube.com/embed/<video_id>
        """
        if self.video_url:
            # Handle the standard YouTube watch URL
            if "watch?v=" in self.video_url:
                return self.video_url.replace("watch?v=", "embed/")

            # Handle YouTube Shorts URLs
            elif "youtube.com/shorts/" in self.video_url:
                return self.video_url.replace("youtube.com/shorts/", "www.youtube.com/embed/")

            # Handle shortened YouTube URLs
            elif "youtu.be/" in self.video_url:
                return self.video_url.replace("youtu.be/", "www.youtube.com/embed/")

        # Default: return as-is, if no recognized pattern is found
        return self.video_url

    class Meta:
        verbose_name = _("Exercício")
        verbose_name_plural = _("Exercícios")

    def __str__(self):
        return self.name


class ProgramExercise(models.Model):
    """The exercise in a program."""
    class ColorChoices(models.TextChoices):
        RED = "#FFCCCC", _("Vermelho")
        GREEN = "#CCFFCC", _("Verde")
        BLUE = "#CCCCFF", _("Azul")
        YELLOW = "#FFFFCC", _("Amarelo")
        PURPLE = "#E5CCFF", _("Roxo")
        PINK = "#FFCCE5", _("Rosa")

    class GroupChoices(models.TextChoices):
        RELEASE = "release", _("Liberação")
        STRETCHING = "stretching", _("Alongamento")
        MOBILITY = "mobility", _("Mobilidade")
        MOTOR_CONTROL = "motor_control", _("Controle Motor")
        STABILITY = "stability", _("Estabilidade")
        POWER = "power", _("Potência")
        STRENGTH = "strength", _("Força")

    class UnitChoices(models.TextChoices):
        REPETITIONS = "repetitions", _("Repetições")
        SECONDS = "seconds", _("Segundos")

    program = models.ForeignKey('TrainingProgram', on_delete=models.CASCADE, verbose_name=_("Programa"))
    exercise = models.ForeignKey('Exercise', on_delete=models.CASCADE, verbose_name=_("Exercício"))
    group = models.CharField(max_length=100, choices=GroupChoices.choices, verbose_name=_("Grupo"), default=GroupChoices.STRENGTH)
    order = models.PositiveIntegerField(verbose_name=_("Ordem"))
    color = models.CharField(max_length=10, choices=ColorChoices.choices, verbose_name=_("Cor"), blank=True, null=True)
    sets = models.PositiveIntegerField(verbose_name=_("Série"))
    repetitions_or_time = models.PositiveIntegerField(verbose_name=_("Qtd. (Repetições ou Tempo)"))
    unit = models.CharField(max_length=15, choices=UnitChoices.choices, verbose_name=_("Unidade"), default=UnitChoices.REPETITIONS)
    load = models.DecimalField(max_digits=5, decimal_places=1, verbose_name=_("Carga (Kg)"), blank=True, null=True)
    observation = models.CharField(max_length=200, verbose_name=_("Observação"), blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True, verbose_name=_("Criado em"))


    class Meta:
        verbose_name = _("Exercício do programa")
        verbose_name_plural = _("Exercícios do programa")

    def __str__(self):
        return f"{self.exercise.name}-{self.program.name}"

life/core/forms.py
from allauth.account.forms import SignupForm, ResetPasswordForm
from django_recaptcha.fields import ReCaptchaField
from django_recaptcha.widgets import ReCaptchaV2Invisible
from django import forms
from django.contrib.auth.forms import UserChangeForm
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django_ckeditor_5.widgets import CKEditor5Widget

from .models import Goal, GoogleAgenda, Notes


class NotesForm(forms.ModelForm):
    class Meta:
        model = Notes
        fields = ('my_notes',)
        widgets = {
            "my_notes": CKEditor5Widget(
                attrs={"class": "django_ckeditor_5"},
            )
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["my_notes"].required = False


class GoalForm(forms.ModelForm):
    class Meta:
        model = Goal
        exclude = ('user', 'matrix')

        widgets = {'start_date': forms.DateInput(attrs={'id': 'flatpickr-date1',
                                                        'class': 'flatpickr'}),
                   'end_date': forms.DateInput(attrs={'id': 'flatpickr-date2',
                                                      'class': 'flatpickr'})
                   }

    def clean(self):
        """Validates that start date must be smaller than end date"""
        super(GoalForm, self).clean()
        start_date = self.cleaned_data['start_date']
        end_date = self.cleaned_data['end_date']
        if start_date and end_date and start_date >= end_date:
            raise ValidationError("Start date must be earlier than end date")


class GoogleAgendaForm(forms.ModelForm):

    agenda_id = forms.CharField(
        label='Google agenda url',
        widget=forms.Textarea(attrs={'class': 'form-control', 'rows': 12})
    )

    class Meta:
        model = GoogleAgenda
        fields = ('agenda_id',)


class UserUpdateForm(UserChangeForm):
    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control custom-name-width'}))
    first_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control custom-name-width'}))
    last_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control custom-name-width'}))

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name')

    def __init__(self, *args, **kwargs):
        super(UserUpdateForm, self).__init__(*args, **kwargs)
        self.fields['password'].widget = forms.HiddenInput()


class CustomSignupForm(SignupForm):
    captcha = ReCaptchaField(widget=ReCaptchaV2Invisible)


class CustomResetPasswordForm(ResetPasswordForm):
    captcha = ReCaptchaField(widget=ReCaptchaV2Invisible)

life/core/views.py
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect

from life.core.forms import GoalForm, UserUpdateForm, GoogleAgendaForm, NotesForm
from life.core.models import Goal, GoogleAgenda, Notes


@login_required(login_url="/accounts/login/")
def home(request):
    user = request.user
    google_agenda = GoogleAgenda.objects.filter(user=user)
    goals = Goal.objects.filter(user=user)
    form = GoalForm()

    has_project_goals = goals.filter(type='pr').exists()
    has_trip_goals = goals.filter(type='tr').exists()
    has_buy_goals = goals.filter(type='by').exists()
    has_do_goals = goals.filter(type='do').exists()

    if request.method == "POST":
        form = GoalForm(request.POST)
        if form.is_valid():
            goal = form.save(commit=False)
            goal.user = request.user
            goal.save()
            form = GoalForm()

    context = {
        'google_agenda': google_agenda,
        'form': form,
        'goals': goals,
        'has_project_goals': has_project_goals,
        'has_trip_goals': has_trip_goals,
        'has_buy_goals': has_buy_goals,
        'has_do_goals': has_do_goals,
    }

    return render(request, 'index.html', context)


# @login_required
# def notes(request):
#     user = request.user
#     try:
#         notes_instance = Notes.objects.get(user=user)
#     except Notes.DoesNotExist:
#         notes_instance = None
#
#     if request.method == "POST":
#         form = NotesForm(request.POST, instance=notes_instance)
#         if form.is_valid():
#             notes_instance = form.save(commit=False)
#             notes_instance.user = request.user
#             notes_instance.save()
#             return redirect('notes')
#     else:
#         form = NotesForm(instance=notes_instance)
#
#     return render(request, 'notes.html', {'form': form})


@login_required
def notes(request):
    user = request.user
    all_notes, created = Notes.objects.get_or_create(user=user)

    if request.method == "POST":
        form = NotesForm(request.POST, instance=all_notes)
        if form.is_valid():
            form.save()
            return redirect('notes')

    else:
        form = NotesForm(instance=all_notes)

    context = {'form': form}

    return render(request, 'notes.html', context)


@login_required
def profile(request):
    user = request.user
    google_agenda, created = GoogleAgenda.objects.get_or_create(user=user)

    if request.method == 'POST':
        google_agenda_form = GoogleAgendaForm(request.POST, instance=google_agenda)
        user_form = UserUpdateForm(request.POST, instance=user)
        if google_agenda_form.is_valid() and user_form.is_valid():
            google_agenda_form.save()
            user_form.save()
            return redirect('home')
    else:
        google_agenda_form = GoogleAgendaForm(instance=google_agenda)
        user_form = UserUpdateForm(instance=user)

    context = {'google_agenda_form': google_agenda_form, 'user_form': user_form}
    return render(request, 'user/profile.html', context)


@login_required
def delete_account(request):
    if request.method == 'POST':
        request.user.delete()
        logout(request)
        return redirect('home')
    else:
        return render(request, 'account/delete_account.html')

@login_required
def edit_goal(request, pk):
    user = request.user
    goal = Goal.objects.get(pk=pk, user=user)

    form = GoalForm(request.POST or None, instance=goal)
    if form.is_valid():
        form.save()
        return redirect('/')

    context = {'pk': pk, 'goal': goal, 'form': form}
    return render(request, 'edit_goal.html', context)


@login_required
def delete_goal(request, pk=None):
    user = request.user
    goal = Goal.objects.get(pk=pk, user=user)
    goal.delete()

    return redirect('home')

life/gym/views.py
from django.contrib.admin.views.decorators import staff_member_required
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.shortcuts import render
from itertools import groupby
from operator import attrgetter
from life.gym.models import TrainingProgram, ProgramExercise
from life.gym.services import group_exercises_by_group


@login_required
def programs(request):
    user = request.user
    training_programs = TrainingProgram.objects.filter(
        user=user, active=True
    ).prefetch_related('programexercise_set__exercise')

    # Group exercises by 'group' in the view
    group_exercises_by_group(training_programs)

    context = {'training_programs': training_programs}
    return render(request, 'gym/series.html', context)


@staff_member_required
def clients_programs(request):
    # Fetch all users who have at least one active TrainingProgram
    users_with_programs = User.objects.filter(trainingprogram__active=True).distinct()

    # Prepare a dictionary to store each user's programs with grouped exercises
    users_training_programs = {}

    for user in users_with_programs:
        # Fetch the training programs for the current user
        training_programs = TrainingProgram.objects.filter(
            user=user, active=True
        ).prefetch_related('programexercise_set__exercise')

        # Group exercises by 'group' for each program
        group_exercises_by_group(training_programs)

        # Add the user's programs to the dictionary
        users_training_programs[user] = training_programs

    # Pass the data to the template
    context = {'users_training_programs': users_training_programs}
    return render(request, "gym/clients_programs.html", context)

life/core/templates/gym/clients_programs.html
{% extends "base.html" %}
{% load static %}
{% block content %}

    <br><br>

    <div class="container">
        <div class="row justify-content-md-center">
            {% for user, training_programs in users_training_programs.items %}
                <div class="col col-md-6">
                    <h5>{{ user.first_name }}'s Programs</h5>
                    {% for program in training_programs %}
                        {% include 'gym/program_card.html' %}
                    {% endfor %}
                </div>
            {% endfor %}
        </div>
    </div>

    <!-- Script to Reset Video in Modal -->
    <script>
        $(".modal").on("hidden.bs.modal", function () {
            $(this).find("iframe").attr("src", $(this).find("iframe").attr("src"));
        });
    </script>

{% endblock content %}

life/core/templates/gym/program_card.html
 <div class="mb-3">
        <!-- Button to toggle collapse -->
        <button
            class="btn btn-primary btn-block text-left"
            type="button"
            data-toggle="collapse"
            data-target="#collapse{{ forloop.counter }}"
            aria-expanded="false"
            aria-controls="collapse{{ forloop.counter }}">
          {{ program.name }}
        </button>

        <!-- Collapsible content -->
        <div class="collapse" id="collapse{{ forloop.counter }}">
          <div class="card card-body mt-2">
            {% for group, exercises in program.grouped_exercises.items %}
              <h5>{{ group|default_if_none:"Uncategorized" }}</h5> <!-- Group Title -->
              <ul class="list-unstyled">
                {% for exercise in exercises %}
                <li style="background-color: {{ exercise.color }}; padding: 10px; margin-bottom: 5px; border-radius: 5px;">
                  <a href="" data-toggle="modal" data-target="#modal{{ exercise.id }}">
                    <strong>{{ exercise.exercise.name }}</strong>
                  </a>
                  - {{ exercise.sets }} x
                  {{ exercise.repetitions_or_time }} {{ exercise.get_unit_display }}
                  {% if exercise.load %}- {{ exercise.load }} kg{% else %}{% endif %}
                    {% if exercise.observation %} ({{ exercise.observation }}) {% endif %}
                </li>
                <!-- Modal for YouTube Video -->
                <div class="modal fade" id="modal{{ exercise.id }}" tabindex="-1" aria-labelledby="modalLabel{{ exercise.id }}" aria-hidden="true">
                  <div class="modal-dialog modal-dialog-centered">
                    <div class="modal-content">
                      <div class="modal-header">
                        <h5 class="modal-title" id="modalLabel{{ exercise.id }}">{{ exercise.exercise.name }}</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                          <span aria-hidden="true">&times;</span>
                        </button>
                      </div>
                      <div class="modal-body">
                       {% if exercise.exercise.video_url %}
                         <div class="embed-responsive embed-responsive-16by9">
                           <iframe
                               class="embed-responsive-item"
                               src="{{ exercise.exercise.embed_url|add:'?rel=0' }}"
                               allowfullscreen></iframe>
                         </div>
                       {% else %}
                         <p>No video available for this exercise.</p>
                       {% endif %}
                      </div>
                      <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                      </div>
                    </div>
                  </div>
                </div>
                <!-- End of Modal -->
                {% endfor %}
              </ul>
            {% endfor %}
          </div>
        </div>
      </div>

life/core/templates/gym/series.html
{% extends "base.html" %}
{% load static %}
{% block content %}

    <br><br>

    <div class="container">
      <div class="row justify-content-md-center">
        <div class="col col-md-6">
          {% for program in training_programs %}
            {% include 'gym/program_card.html' %}
          {% endfor %}
        </div>
      </div>
    </div>

    <!-- Script to Reset Video in Modal -->
    <script>
        $(".modal").on("hidden.bs.modal", function () {
            $(this).find("iframe").attr("src", $(this).find("iframe").attr("src"));
        });
    </script>

{% endblock content %}