life/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from life.core import views

urlpatterns = [
    # path('summernote/', include('django_summernote.urls')),
    path('profile/', views.profile, name='profile'),
    path('account/delete_account/', views.delete_account, name='delete_account'),
    path('edit_goal/<pk>', views.edit_goal, name='edit_goal'),
    path('notes/', views.notes, name='notes'),
    path('delete_goal/<pk>', views.delete_goal, name='delete_goal'),
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('gym/', include('life.gym.urls')),
    path('', views.home, name='home'),
]

urlpatterns += [
    path("ckeditor5/", include('django_ckeditor_5.urls'), name="ck_editor_5_upload_file"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

life/core/models.py
from django.contrib.auth.models import User
from django.db import models
from django_ckeditor_5.fields import CKEditor5Field

from life.core import services


class Goal(models.Model):

    PROJECT, TRIP, BUY, DO = 'pr', 'tr', 'by', 'do'
    TYPES = ((PROJECT, 'Project'), (TRIP, 'Trip'), (BUY, 'Buy'), (DO, 'Do'))

    HIGH, LOW = 'hi', 'lo'
    EFFORTS = ((HIGH, 'High'), (LOW, 'Low'))

    PERSONAL, PROFESSIONAL = 'pe', 'pr'
    AREAS = ((PERSONAL, 'Personal'), (PROFESSIONAL, 'Professional'))

    PRIORITIES = ((1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'))

    user = models.ForeignKey(User, on_delete=models.CASCADE)

    name = models.CharField(max_length=255)
    description = models.TextField(blank=True, null=True)

    type = models.CharField(max_length=2, choices=TYPES)
    effort = models.CharField(max_length=2, choices=EFFORTS)
    area = models.CharField(max_length=2, choices=AREAS, default=PERSONAL)
    important = models.PositiveSmallIntegerField(choices=PRIORITIES, default='1')
    urgent = models.PositiveSmallIntegerField(choices=PRIORITIES, default='1')
    matrix = models.PositiveSmallIntegerField(default=0)

    cost = models.DecimalField(max_digits=12, decimal_places=2, null=True, blank=True)
    start_date = models.DateField()
    end_date = models.DateField(null=True, blank=True)
    next = models.BooleanField(default=False)
    completed = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)

    def save(self, *args, **kwargs):
        self.matrix = self.matrix_calculation()
        return super(Goal, self).save(*args, **kwargs)

    def matrix_calculation(self):
        matrix = self.important * self.urgent
        return matrix

    def __str__(self):
        return self.name


class GoogleAgenda(models.Model):

    user = models.OneToOneField(User, on_delete=models.CASCADE)
    agenda_id = models.TextField()
    agenda_clean = models.TextField(blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def save(self, *args, **kwargs):
        self.agenda_clean = services.extract_src_ctz(self.agenda_id)
        return super(GoogleAgenda, self).save(*args, **kwargs)

    def __str__(self):
        return f"{self.user}'s Google agenda"


class Notes(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    my_notes = CKEditor5Field(null=True, blank=True)

    def __str__(self):
        return f"{self.user}'s Notes"

    class Meta:
        verbose_name_plural = 'Notes'

life/core/forms.py
from allauth.account.forms import SignupForm, ResetPasswordForm
from django_recaptcha.fields import ReCaptchaField
from django_recaptcha.widgets import ReCaptchaV2Invisible
from django import forms
from django.contrib.auth.forms import UserChangeForm
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django_ckeditor_5.widgets import CKEditor5Widget

from .models import Goal, GoogleAgenda, Notes


class NotesForm(forms.ModelForm):
    class Meta:
        model = Notes
        fields = ('my_notes',)
        widgets = {
            "my_notes": CKEditor5Widget(
                attrs={"class": "django_ckeditor_5"},
            )
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["my_notes"].required = False


class GoalForm(forms.ModelForm):
    class Meta:
        model = Goal
        exclude = ('user', 'matrix')

        widgets = {'start_date': forms.DateInput(attrs={'id': 'flatpickr-date1',
                                                        'class': 'flatpickr'}),
                   'end_date': forms.DateInput(attrs={'id': 'flatpickr-date2',
                                                      'class': 'flatpickr'})
                   }

    def clean(self):
        """Validates that start date must be smaller than end date"""
        super(GoalForm, self).clean()
        start_date = self.cleaned_data['start_date']
        end_date = self.cleaned_data['end_date']
        if start_date and end_date and start_date >= end_date:
            raise ValidationError("Start date must be earlier than end date")


class GoogleAgendaForm(forms.ModelForm):

    agenda_id = forms.CharField(
        label='Google agenda url',
        widget=forms.Textarea(attrs={'class': 'form-control', 'rows': 12})
    )

    class Meta:
        model = GoogleAgenda
        fields = ('agenda_id',)


class UserUpdateForm(UserChangeForm):
    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control custom-name-width'}))
    first_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control custom-name-width'}))
    last_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control custom-name-width'}))

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name')

    def __init__(self, *args, **kwargs):
        super(UserUpdateForm, self).__init__(*args, **kwargs)
        self.fields['password'].widget = forms.HiddenInput()


class CustomSignupForm(SignupForm):
    captcha = ReCaptchaField(widget=ReCaptchaV2Invisible)


class CustomResetPasswordForm(ResetPasswordForm):
    captcha = ReCaptchaField(widget=ReCaptchaV2Invisible)

life/core/views.py
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect

from life.core.forms import GoalForm, UserUpdateForm, GoogleAgendaForm, NotesForm
from life.core.models import Goal, GoogleAgenda, Notes


@login_required(login_url="/accounts/login/")
def home(request):
    user = request.user
    google_agenda = GoogleAgenda.objects.filter(user=user)
    goals = Goal.objects.filter(user=user)
    form = GoalForm()

    has_project_goals = goals.filter(type='pr').exists()
    has_trip_goals = goals.filter(type='tr').exists()
    has_buy_goals = goals.filter(type='by').exists()
    has_do_goals = goals.filter(type='do').exists()

    if request.method == "POST":
        form = GoalForm(request.POST)
        if form.is_valid():
            goal = form.save(commit=False)
            goal.user = request.user
            goal.save()
            form = GoalForm()

    context = {
        'google_agenda': google_agenda,
        'form': form,
        'goals': goals,
        'has_project_goals': has_project_goals,
        'has_trip_goals': has_trip_goals,
        'has_buy_goals': has_buy_goals,
        'has_do_goals': has_do_goals,
    }

    return render(request, 'index.html', context)


# @login_required
# def notes(request):
#     user = request.user
#     try:
#         notes_instance = Notes.objects.get(user=user)
#     except Notes.DoesNotExist:
#         notes_instance = None
#
#     if request.method == "POST":
#         form = NotesForm(request.POST, instance=notes_instance)
#         if form.is_valid():
#             notes_instance = form.save(commit=False)
#             notes_instance.user = request.user
#             notes_instance.save()
#             return redirect('notes')
#     else:
#         form = NotesForm(instance=notes_instance)
#
#     return render(request, 'notes.html', {'form': form})


@login_required
def notes(request):
    user = request.user
    all_notes, created = Notes.objects.get_or_create(user=user)

    if request.method == "POST":
        form = NotesForm(request.POST, instance=all_notes)
        if form.is_valid():
            form.save()
            return redirect('notes')

    else:
        form = NotesForm(instance=all_notes)

    context = {'form': form}

    return render(request, 'notes.html', context)


@login_required
def profile(request):
    user = request.user
    google_agenda, created = GoogleAgenda.objects.get_or_create(user=user)

    if request.method == 'POST':
        google_agenda_form = GoogleAgendaForm(request.POST, instance=google_agenda)
        user_form = UserUpdateForm(request.POST, instance=user)
        if google_agenda_form.is_valid() and user_form.is_valid():
            google_agenda_form.save()
            user_form.save()
            return redirect('home')
    else:
        google_agenda_form = GoogleAgendaForm(instance=google_agenda)
        user_form = UserUpdateForm(instance=user)

    context = {'google_agenda_form': google_agenda_form, 'user_form': user_form}
    return render(request, 'user/profile.html', context)


@login_required
def delete_account(request):
    if request.method == 'POST':
        request.user.delete()
        logout(request)
        return redirect('home')
    else:
        return render(request, 'account/delete_account.html')

@login_required
def edit_goal(request, pk):
    user = request.user
    goal = Goal.objects.get(pk=pk, user=user)

    form = GoalForm(request.POST or None, instance=goal)
    if form.is_valid():
        form.save()
        return redirect('/')

    context = {'pk': pk, 'goal': goal, 'form': form}
    return render(request, 'edit_goal.html', context)


@login_required
def delete_goal(request, pk=None):
    user = request.user
    goal = Goal.objects.get(pk=pk, user=user)
    goal.delete()

    return redirect('home')

life/core/templates/401.html
{% extends "base.html" %}
{% load static %}

{% block content %}

    <div class="row justify-content-md-center">
        <div class="col-md-8">

            <h1 class="mt-5">Error 401</h1>
            <h3 class="ml-5 my-5">Authentication required</h3>
            <h5 class="ml-5">Please verify your login credentials.</h5>

        </div>
    </div>

{% endblock content %}

life/core/templates/502.html
{% extends "base.html" %}
{% load static %}

{% block content %}

    <div class="row justify-content-md-center">
        <div class="col-md-8">

            <h1 class="mt-5">Error 502</h1>
            <h3 class="ml-5 my-5">Service temporarily overloaded</h3>
            <h5 class="ml-5">The server encountered a temporary error and could not complete your request</h5>
            <h5 class="ml-5">Please try again or contact your system administrator</h5>

        </div>
    </div>

{% endblock content %}

life/core/templates/503.html
{% extends "base.html" %}
{% load static %}

{% block content %}

    <div class="row justify-content-md-center">
        <div class="col-md-8">

            <h1 class="mt-5">Error 503</h1>
            <h3 class="ml-5 my-5">Service Unavailable</h3>
            <h5 class="ml-5">An issue occurred with one or more services required to run the application.</h5>

        </div>
    </div>

{% endblock content %}

life/core/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <title>{% block title %}Life{% endblock title %}</title>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <meta name="description" content="Project description">
        <meta name="author" content="Guilherme Forton Viotti">
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />

        <!-- Favicon -->
        <link rel="shortcut icon" href="https://res.cloudinary.com/dpazaz3ig/image/upload/v1680506725/life/workspaces.ico">

        <!-- CSS -->
        <link rel="stylesheet" href="{% static 'css/main.css' %}">

        <!-- Material font (Roboto) and Material icons -->
        <link rel="preconnect" href="https://fonts.gstatic.com/" crossorigin>
        <link rel="preconnect" href="https://cdn.jsdelivr.net/" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Roboto+Mono:wght@300;400;700&family=Roboto+Slab:wght@300;400;700&family=Roboto:ital,wght@0,300;0,400;0,500;0,700;1,300;1,400;1,500;1,700&display=swap" rel="stylesheet" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Material+Icons+Outlined" rel="stylesheet" crossorigin>

        <!-- Material CSS -->
        <link rel="stylesheet" href="{% static 'css/material.min.css' %}" crossorigin>

        <!-- Optional Material CSS for Plugins -->
        <link href="https://cdn.jsdelivr.net/gh/djibe/material@4.6.1-1.0/css/material-plugins.min.css" rel="stylesheet" crossorigin>

    </head>

    <body>

	    {% include 'nav.html' %}

        <div class="container-fluid main-container">
            {% block content %}
            {% endblock content %}
        </div>

        <!-- Replace jQuery Slim with full version of jQuery -->
        <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin></script>
    
    
        <!-- jQuery, Bootstrap Bundle (includes Popper) and Material -->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js" integrity="sha256-fgLAgv7fyCGopR/gBNq2iW3ZKIdqIcyshnUULC4vex8=" crossorigin></script>
        <script src="{% static 'js/material.min.js' %}" crossorigin></script>
    
        <!-- DataTables JS (Bootstrap 4 version) and its dependencies -->
        <script src="https://cdn.jsdelivr.net/npm/pdfmake@0.1.68/build/pdfmake.min.js" integrity="sha256-Xf58sgO5ClVXPyDzPH+NtjN52HMC0YXBJ3rp8sWnyUk=" crossorigin></script>
        <script src="https://cdn.jsdelivr.net/npm/pdfmake@0.1.68/build/vfs_fonts.js" integrity="sha256-vEmrkqA2KrdjNo0/IWMNelI6jHuWAOkIJxGf88r4iic=" crossorigin></script>
        <script src="https://cdn.datatables.net/v/bs4/jszip-2.5.0/dt-1.10.22/b-1.6.5/b-colvis-1.6.5/b-flash-1.6.5/b-html5-1.6.5/b-print-1.6.5/cr-1.5.2/fc-3.3.1/r-2.2.6/rr-1.2.7/sl-1.3.1/datatables.min.js" crossorigin></script>
    
        <!-- jQuery for date flatpicker -->
        <script src="https://cdn.jsdelivr.net/npm/flatpickr@4.6.6/dist/flatpickr.min.js" integrity="sha256-BSZ2gjTJLE5ZEGH1e6beyHYNOITz6M26XFre9lEBdx8=" crossorigin></script>
        
        
    <script>
        flatpickr('#flatpickr-date1', {dateFormat: "d/m/Y"})
        flatpickr('#flatpickr-date2', {dateFormat: "d/m/Y"})
    </script>

    <script>

        document.addEventListener('DOMContentLoaded', function() {
            // Hide the goal elements by default
            var goals = document.querySelectorAll('.goal');
            for (var i = 0; i < goals.length; i++) {
                goals[i].style.display = 'none';
            }

            // Add an event listener to the "Show All" button
            document.getElementById('show-all-button').addEventListener('click', function() {
                for (var i = 0; i < goals.length; i++) {
                    goals[i].style.display = goals[i].style.display === 'none' ? '' : 'none';
                }
            });
        });


    </script>

        <script>
	    {% block javascript %}
	    {% endblock javascript %}
	</script>

    </body>
</html>

life/core/templates/create_item_modal.html
<div class="modal fade" id="create_item" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="create_item">Create new item</h5>
            </div>
            <div class="modal-body">
                {{ form.non_field_errors }}
                <form action="" method="post">

                    {% csrf_token %}
                    <table>
                        {{ form.as_table }}
                    </table>
                    <button class="btn btn-outline-dark" type="submit">Save</button>

                </form>
            </div>

        </div>
    </div>
</div>

life/core/templates/edit_goal.html
{% extends "base.html" %}
{% load static %}
{% block content %}

    <div class="row justify-content-center pt-5">
        <div class="col col-4">

            <h3 class="text-center">Editing "{{ goal.name }}"</h3>
            <p></p>
            {{ form.non_field_errors }}
            <form action="" method="post">
                {% csrf_token %}

                <table>
                    {{ form.as_table }}
                </table>

                <button class="btn btn-outline-dark" type="submit">Save</button>
            </form>
            <br>
            <a class="btn btn-outline-danger btn-sm" href="{% url 'delete_goal' goal.id %}">Delete</a>

        </div>
    </div>

{% endblock content %}

life/core/templates/index.html
{% extends "base.html" %}
{% load static %}
{% block content %}

    <br>
    <div class="row align-items-center">
        <div class="col-auto">
            <button type="button" class="btn btn-icon btn-sm bg-light-1" data-toggle="modal" data-target="#create_item">
                <span class="material-icons">add_circle_outline</span>
            </button>
        </div>
        <div class="col-auto">
            <form action="{% url 'home' %}" method="post" class="d-inline">
                {% csrf_token %}
                <button id="show-all-button" class="btn btn-sm btn-dark" type="button">Toggle 'Done'</button>
            </form>
        </div>
        <div class="col-auto">
            <a class="btn btn-sm btn-dark" data-toggle="collapse" href="#collapseAgenda" role="button" aria-expanded="false" aria-controls="collapseAgenda">
                Agenda
            </a>
        </div>
    </div>


    <div class="collapse" id="collapseAgenda">
        <div class="card card-body">
            <iframe class="text-center" src="https://calendar.google.com/calendar/embed?height=600&wkst=1&bgcolor=%23ffffff&ctz=Europe%2FLondon&showTitle=0&showDate=1&showPrint=0&showTabs=1&showCalendars=1&mode=MONTH&{{ google_agenda.0.agenda_id }}&color=%234285F4&color=%238E24AA&color=%23D50000&color=%23F09300&color=%23616161&color=%23616161&color=%230B8043"
                    style="border:solid 1px #777" width="1440" height="600" frameborder="0" scrolling="no"></iframe>
        </div>
    </div>

    <div class="row justify-content-center mt-3">
        <div class="col-sm-6">
            {% if has_trip_goals%}
                <p class="text-center text-primary">TRIPS</p>
                {% include 'trips.html' %}
            {% endif %}
        </div>
        <div class="col-sm-6">
            {% if has_do_goals%}
                <p class="text-center text-primary">TO DO</p>
                {% include 'todo.html' %}
            {% endif %}
        </div>
    </div>
    <br>
    <div class="row justify-content-center">
        <div class="col-sm-6">
            {% if has_project_goals%}
                <p class="text-center text-primary">PROJECTS</p>
                {% include 'projects.html' %}
            {% endif %}
        </div>

        <div class="col-sm-6">
            {% if has_buy_goals%}
                <p class="text-center text-primary">TO BUY</p>
                {% include 'tobuy.html' %}
            {% endif %}
        </div>
    </div>

{% endblock content %}

life/core/templates/nav.html
{% include "create_item_modal.html" %}

<nav class="navbar navbar-light fixed-top bg-light-2">

    <a class="navbar-brand" href="/">
        <span class="material-icons-outlined mr-1">
            workspaces
        </span>
        Life
    </a>

    <div class="form-inline">
        {% if user.is_authenticated and user.is_staff %}
            <a class="btn btn-icon btn-sm ml-2 bg-light-1" href="{% url 'admin:index' %}">
                <span class="material-icons red">lock_open</span>
            </a>
            <a class="btn btn-primary ml-2" href="{% url 'clients_programs' %}">Clients</a>
        {% endif %}

        {% if user.is_authenticated %}

            <a class="btn btn-dark ml-2" href="{% url 'gym' %}">Gym</a>
            <a class="btn btn-dark ml-2" href="{% url 'notes' %}">Notes</a>

        {% endif %}

        {% if not user.is_authenticated %}
            <a class="btn btn-outline-dark ml-2" href="{% url 'account_login' %}">Login / Register</a>
        {% else %}
            <div class="">
                <a class="btn btn-outline-dark ml-2" href="{% url 'profile' %}">Profile</a>
                <a class="btn btn-outline-dark ml-2" href="{% url 'account_logout' %}">Logout</a>
            </div>
        {% endif %}

    </div>

</nav>

life/core/templates/notes.html
{% extends "base.html" %}
{% load static %}
{% block content %}

    <div class="row justify-content-center my-3">
        <div class="col">

            <form method="post">
                {% csrf_token %}
                <button class="btn btn-xs btn-outline-dark" type="submit">Save</button>
                
                {{ form.non_field_errors }}
                {% for field in form %}
                    {{ field.errors }}
                    {{ field }}
                {% endfor %}
            
                {{ form.media }}
            
                <button class="btn btn-outline-dark my-3" type="submit">Save</button>
            </form>
            
        </div>
    </div>

{% endblock content %}

life/core/templates/projects.html
<div class="row justify-content-center">

    <div class="col-sm-12">
        <table class="table table-borderless table-hover table-sm">
            <thead>
            <tr>
                <th scope="col">Type</th>
                <th scope="col">Name</th>
                <th scope="col">Cost</th>
                <th scope="col">Date</th>
            </tr>
            </thead>
            <tbody>
            {% for goal in goals|dictsortreversed:"matrix" %}
                {% if goal.get_type_display == "Project" %}
                    <tr {% if goal.completed %}class="goal bg-danger"{% elif goal.next %}class="bg-success"{% endif %}>
                        <td>{{ goal.get_area_display }}</td>
                        <td><span class="badge badge-light">{{ goal.matrix_calculation }}</span>
                            <a class="text-decoration-none text-reset" href="{% url 'edit_goal' goal.id %}">
                                <span class="badge">{{ goal.name }}</span>
                            </a>
                        </td>
                        <td>{{ goal.cost }}</td>
                        <td>{{ goal.start_date|date:"SHORT_DATE_FORMAT" }}
                            {% if goal.end_date %} - {{ goal.end_date|date:"SHORT_DATE_FORMAT" }}{% endif %}
                        </td>
                    </tr>
                {% endif %}
            {% endfor %}
            </tbody>
        </table>
    </div>

</div>

life/core/templates/tobuy.html
<div class="row justify-content-center">

    <div class="col-sm-12">
        <table class="table table-borderless table-hover table-sm">
            <thead>
            <tr>
                <th scope="col">Effort</th>
                <th scope="col">Name</th>
                <th scope="col">Cost</th>
                <th scope="col">Date</th>
            </tr>
            </thead>
            <tbody>
            {% for goal in goals|dictsortreversed:"matrix" %}
                {% if goal.get_type_display == "Buy" %}
                    <tr {% if goal.completed %}class="goal bg-danger"{% elif goal.next %}class="bg-success"{% endif %}>
                        <td>{{ goal.get_effort_display }}</td>
                        <td><span class="badge badge-light">{{ goal.matrix_calculation }}</span>
                            <a class="text-decoration-none text-reset" href="{% url 'edit_goal' goal.id %}">
                                <span class="badge">{{ goal.name }}</span>
                            </a>
                        </td>
                        <td>{{ goal.cost }}</td>
                        <td>{{ goal.start_date|date:"SHORT_DATE_FORMAT" }}
                            {% if goal.end_date %} - {{ goal.end_date|date:"SHORT_DATE_FORMAT" }}{% endif %}
                        </td>
                    </tr>
                {% endif %}
            {% endfor %}
            </tbody>
        </table>
    </div>

</div>

life/core/templates/todo.html
<div class="row justify-content-center">

    <div class="col-sm-12">
        <table class="table table-borderless table-hover table-sm">
            <thead>
            <tr>
                <th scope="col">Effort</th>
                <th scope="col">Name</th>
                <th scope="col">Cost</th>
                <th scope="col">Date</th>
            </tr>
            </thead>
            <tbody>
            {% for goal in goals|dictsortreversed:"matrix" %}
                {% if goal.get_type_display == "Do" %}
                    <tr {% if goal.completed %}class="goal bg-danger"{% elif goal.next %}class="bg-success"{% endif %}>
                        <td>{{ goal.get_effort_display }}</td>
                        <td><span class="badge badge-light">{{ goal.matrix_calculation }}</span>
                            <a class="text-decoration-none text-reset" href="{% url 'edit_goal' goal.id %}">
                                <span class="badge">{{ goal.name }}</span>
                            </a>
                        </td>
                        <td>{{ goal.cost }}</td>
                        <td>{{ goal.start_date|date:"SHORT_DATE_FORMAT" }}
                            {% if goal.end_date %} - {{ goal.end_date|date:"SHORT_DATE_FORMAT" }}{% endif %}
                        </td>
                    </tr>
                {% endif %}
            {% endfor %}
            </tbody>
        </table>
    </div>

</div>

life/core/templates/trips.html
<div class="row justify-content-center">

    <div class="col-sm-12">
        <table class="table table-borderless table-hover table-sm">
            <thead>
            <tr>
                <th scope="col">Name</th>
                <th scope="col">Cost</th>
                <th scope="col">Date</th>
            </tr>
            </thead>
            <tbody>
            {% for goal in goals|dictsortreversed:"matrix" %}
                {% if goal.get_type_display == "Trip"%}
                    <tr {% if goal.completed %}class="goal bg-danger"{% elif goal.next %}class="bg-success"{% endif %}>
                        <td><span class="badge badge-light">{{ goal.matrix_calculation }}</span>
                            <a class="text-decoration-none text-reset" href="{% url 'edit_goal' goal.id %}">
                                <span class="badge">{{ goal.name }}</span>
                            </a>
                        </td>
                        <td>{{ goal.cost }}</td>
                        <td>{{ goal.start_date|date:"SHORT_DATE_FORMAT" }}
                            {% if goal.end_date %} - {{ goal.end_date|date:"SHORT_DATE_FORMAT" }}{% endif %}
                        </td>
                    </tr>
                {% endif %}
            {% endfor %}
            </tbody>
        </table>
    </div>

</div>